### ISSUE TITLE
Bintray repo is down

### ISSUE THREAD

**Issue by wpopovich** [sbt/sbt-javaagent#23]
Now that bintray is deprecated, it seems that the repos are being taken down. Attempting to compile with this plugin enabled produces the following error 

```
download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.6/ivys/ivy.xml (Server returned HTTP response code: 403 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.6/ivys/ivy.xml) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.6/ivys/ivy.xml
```

You guys think you could publish this somwhere else?

**Comment by wpopovich** [comment]
More info on the bintray situation here https://status.bintray.com/ and https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by pshemass** [comment]
any update on that? I cannot find any repo that hosting this plugin

**Comment by pvlugter** [comment]
All sbt plugins already published to the sbt community repo on bintray have been migrated to an artifactory repository.

The redirects for https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases have been updated to this new repository.

More details in https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1 and https://github.com/sbt/sbt/issues/6294.

Here's this plugin at its redirected location: https://scala.jfrog.io/artifactory/sbt-plugin-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.6/

**Comment by julienrf** [comment]
Version 0.1.7 should be available on Sonatype. Please re-open this issue if that did not work.
