### ISSUE TITLE
Packages missing from any repositroy

### ISSUE THREAD

**Issue by KamilPostrozny** [sbt/sbt-javaagent#24]
Hey, plugin is gone today, you can't find it in any repository.

**Comment by KannarFr** [comment]
Same issue here.

**Comment by KannarFr** [comment]
Related to https://github.com/spray/sbt-revolver/issues/112.

**Comment by KannarFr** [comment]
As the availability of https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases is currently having issues without any resolution date.

Can we expect this plugin to be pushed to `com.github.sbt` as it's done for `sbt-native-packager` here: https://github.com/sbt/sbt-native-packager/blob/master/.github/workflows/release.yml#L61.

**Comment by mkurz** [comment]
This library should get published to Maven central instead using sbt-ci-release and newgroupId `com.github.sbt` IMHO.

**Comment by KannarFr** [comment]
@eed3si9n Hi, as member of sbt github organization, can you make a github action to publish sbt-javaagent to sbt.github.com?

**Comment by eed3si9n** [comment]
I don't know the state or popularity of this plugin, but ideally there should be someone or some party maintaining it before I start sending pull requests. I did that for sbt-sdlc (https://github.com/sbt/sbt-sdlc/pulls?q=is%3Apr+is%3Aclosed) as an example, but anyone can follow the pattern and send the PRs to this plugin too.

**Comment by KannarFr** [comment]
Sure I'll do it easily.
