### ISSUE TITLE
Is this broken in sbt 1.9.7?

### ISSUE THREAD

**Issue by jakobmerrild** [sbt/sbt-javaagent#28]
We use this plugin to add a prometheus exporter. However, after upgrading to sbt version 1.9.7 it seems to no longer work.

Wondering if the plugin in general doesn't work with 1.9.7 or if there's something else wrong

Here's our build.sbt definition
```scala
javaAgents += JavaAgent(
  "io.prometheus.jmx" % "jmx_prometheus_javaagent" % "0.20.0",
  arguments = "${PROMETHEUS_PORT:-1936}:/app/prometheus-exporter.yaml"
)
```

**Comment by Marcus-Rosti** [comment]
I'll second this, I'm trying to get dd-agent-java working and it's not pulling it in

**Comment by Marcus-Rosti** [comment]
```
addSbtPlugin("org.typelevel" % "sbt-fs2-grpc" % "2.7.11")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.github.sbt" % "sbt-javaagent" % "0.1.7")
```
with
```
lazy val server = project
  .in(file("server"))
  .enablePlugins(JavaServerAppPackaging, DockerPlugin, JavaAgent)
  .dependsOn(`protobuf`)
  .settings(
    name := "server",
    Compile / run / mainClass := Some("com.mrosti.Server"),
    dockerBaseImage := "amazoncorretto:21-alpine3.18",
    dockerExposedPorts ++= Seq(50051),
    javaAgents += "com.datadoghq" % "dd-java-agent" % "1.21.0",
...
)

**Comment by rlemaitre-ledger** [comment]
I have the same issue here with the opentelemetry agent. After upgrading to sbt `1.9.7`, the agent is not passed to runtime.

The only difference in the generated script is 
```diff
- addJava "-javaagent:${app_home}/../opentelemetry-javaagent/opentelemetry-javaagent-1.31.0.jar" 
+
```

**Comment by Marcus-Rosti** [comment]
<img width="376" alt="Screenshot 2023-10-24 at 11 25 11 AM" src="https://github.com/sbt/sbt-javaagent/assets/8094255/3c8cab16-b0ec-4263-b4a3-40e2ce87dbe0">
It won't even download unless I put it at the top level of the multimodule build
```scala
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "3.3.1"

enablePlugins(JavaAgent, DockerPlugin, AshScriptPlugin, JavaServerAppPackaging)
javaAgents += "com.datadoghq" % "dd-java-agent" % "1.21.0"

lazy val root = (project in file("."))
...
lazy val server (project in file("server"))
```

**Comment by Marcus-Rosti** [comment]
There's some bizarre interaction between native-packager, sbt, and javaagent

**Comment by Marcus-Rosti** [comment]
Cats breaks it

**Comment by Marcus-Rosti** [comment]
@eed3si9n Here's a minimalish repro case: https://github.com/Marcus-Rosti/javaagent-bug


```
[info] Main Scala API documentation to /Users/mrosti/src/mrosti/javaagent-bug/app/target/scala-3.3.1/api...
[warn] -- Warning: core/jvm/src/main/scala/cats/effect/IOApp.scala:592:14 -------------
[warn] No DRI found for query: IOApp.Simple!.run:cats\.effect\.IO[Unit]*
[warn] one warning found
[warn] Following generated file paths might not be compatible with Jekyll:
[warn] _empty_/Main$
[warn] If using GitHub Pages consider adding a ".nojekyll" file.
```

**Comment by pvlugter** [comment]
> Cats breaks it?
> Here's a minimalish repro case: https://github.com/Marcus-Rosti/javaagent-bug

Won't be a cats dependency that breaks it. The example has this:

```scala
libraryDependencies := Seq(
  "org.typelevel" %% "cats-effect" % "3.5.2",
)
```

The plugin adds the agent to library dependencies, and the `:=` is overriding that. Use `++=` instead.

**Comment by pvlugter** [comment]
The bug here is that the javaagent is not being added to the native packager `bashScriptExtraDefines`. There's a dynamic dependency on `JavaAppPackaging`, but this setting is from `BashStartScriptPlugin`. So it will be that the order of auto plugins being applied has changed with sbt 1.9.7. @eed3si9n not a bug in sbt. I can update so the packaging plugin here also depends on `BashStartScriptPlugin` as it should.

**Comment by pvlugter** [comment]
Fix released in version `0.1.8`.

**Comment by Marcus-Rosti** [comment]
thanks so much! I thought I was going crazy

**Comment by Marcus-Rosti** [comment]
I can confirm this worked

**Comment by jakobmerrild** [comment]
Thanks @pvlugter and @Marcus-Rosti for following up on this
